### ISSUE TITLE
[CHORE] Provide a pre-build container for NGINX 🧹

### ISSUE THREAD

**Issue by UnclePhil** [SquirrelCorporation/SquirrelServersManager#102]
**Describe the bug**
Please do not include a build  in a production level docker-compose.

**Logs**
unable to prepare context: path "./proxy" not found

**To Reproduce**
1. create a ssm dir
2. create a docker-compose.yml based on your production sample 
3. create a .env based on your .env
4. docker compose up 
and after the pulling of some image, you have the nice error message

`unable to prepare context: path "./proxy" not found`

**Expected behavior**
The download of a prepared ssm proxy

**(please complete the following information):**
 - OS: ubuntu 24
 - Browser NA
 - Version NA

**Comment by SquirrelDeveloper** [comment]
Hi @UnclePhil . As a workaround, for now, you must git clone the project, and, so the directory /proxy/* exists, with the correct configuration file and do the docker-compose up inside.

I may in the future provide a NGINX image pre-packaged in the near future

**Comment by UnclePhil** [comment]
BTW, my solution on docker swarm is to provide  some config settings.
``` 
Services:
  entry:
    restart: unless-stopped
    image: nginx:1.25.5
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
      - source: custom.html
        target: /usr/share/nginx/html/custom.html
    networks:
      - proxy
      - apps
    ports:
      - "8000:8000"
    depends_on:
      - client
      - mongo
      - server
      - redis
     ...
```
