### ISSUE TITLE
[BUG] Unable to create or setup an admin account

### ISSUE THREAD

**Issue by SuperMario22922** [SquirrelCorporation/SquirrelServersManager#138]
**Describe the bug**
When i setup the docker container by git cloning then doing docker compose up, i open it in the browser and it just brings me to the sign in screen but the thing is it never asked me to sign up or create an account

** Logs **
no logs since can't login

**To Reproduce**
1. docker compose up
2. open browser
3. See sign in screen

**Expected behavior**
should be able to sign up first

**Screenshots**
![CleanShot 2024-07-22 at 16 26 41@2x](https://github.com/user-attachments/assets/a13295a0-ed49-4cd2-a6c2-1310ba8e2a2f)
![CleanShot 2024-07-22 at 16 26 51@2x](https://github.com/user-attachments/assets/1956e233-39fd-4294-a1dc-a3f13980d61a)

**(please complete the following information):**
 - OS: raspberry pi server, accessing the ui on a mac
 - Browser firefox

**Comment by SquirrelDeveloper** [comment]
Hi @SuperMario22922 , could you post an extract of the logs please? Regards

**Comment by kraduk** [comment]
I have the same problem. If you want logs posting you need to tell us which logs and from where, as there are a few containers running and the docs are sparse at the moment

**Comment by kraduk** [comment]
fixed my issue, i am using in via portainer, and want to use traefik as a replacement for rev proxy. I wasnt passing some env var correctly

this is now working ignore the traefik labels as it WIP

Point still stands though better comments from devs required it you want adoption

```yaml

networks:
  traefik:
    external: true
  squirrel:
  

services:
  proxy:
    restart: unless-stopped
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-proxy:latest"
    ports:
      - "18000:8000"
    networks:
      - traefik
      - squirrel
    depends_on:
      - client
      - mongo
      - server
      - redis
    labels:
      traefik.docker.network: traefik
      traefik.enable: 'true'
      traefik.http.routers.squirrel.entrypoints: https
      traefik.http.routers.squirrel.rule: Host(`{x:squirrel.docker.krad.uk}`)
      traefik.http.routers.squirrel.tls: 'true'
      traefik.http.services.squirrel.loadbalancer.server.port: '8000'
      traefik.http.services.squirrel.loadbalancer.server.scheme: http
  mongo:
    labels:
      traefik.enable: 'false'
    container_name: mongo-ssm
    image: mongo
    restart: unless-stopped
    volumes:
      - /opt/squirrel/db:/data/db
    command: --quiet 
    networks:
      - squirrel
  redis:
    labels:
      traefik.enable: 'false'
    container_name: cache-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - /opt/squirrel/redis:/data
    command: --save 60 1
    networks:
      - squirrel
  server:
    labels:
      traefik.enable: 'false'
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-server:latest"
    restart: unless-stopped
    external_links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: production
      SECRET: ${SECRET}
      SALT: ${SALT}
      VAULT_PWD: ${VAULT_PWD}
      DB_HOST: mongo
      DB_NAME: ssm
      DB_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - /opt/squirrel/playbooks:/playbooks
    networks:
      - squirrel
  client:
    labels:
      traefik.enable: 'false'
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-client:latest"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - squirrel
```
