### ISSUE TITLE
[FEATURE] Agent in docker

### ISSUE THREAD

**Issue by Buco7854** [SquirrelCorporation/SquirrelServersManager#298]
Would it be possible to actually dockerize the agent? I'm having issues with the agents (nvm path not found etc...) and I thought putting the agent in a container would solve this kind of issue.

Would also be cleaner than installing things directly on the agent's host and would make sure that the uninstall process would be "total".

**Comment by SquirrelDeveloper** [comment]
Hi @Buco7854 . You are right, as I am not satisfied with the way the agent work today. Dockerizing it could be a challenge to access fully the underlying system, but it will definitely change in the near future. Keeping the issue opened to allow discussion

**Comment by Buco7854** [comment]
Can't really talk for sure but isn't it possible to access host system info py mounting /proc for example?

**Comment by SquirrelDeveloper** [comment]
You are probably right, I will have to take a good look at the libs the agent is using ("system information" among other things
)

**Comment by Buco7854** [comment]
I run netdata in a docker container and they mount the whole file system in /host. So it's probably possible since they do it.

But yes, I don't know exactly how and I cannot really look right now.

**Comment by SquirrelDeveloper** [comment]
Hi @Buco7854 ; I have published an experimental docker version of the agent, https://github.com/SquirrelCorporation/SquirrelServersManager-Agent

**Comment by Buco7854** [comment]
Thanks a lot, will probably fix my issue, any ETA on production?

**Comment by SquirrelDeveloper** [comment]
@Buco7854 The plan is to offer the choice in the UI of the agent method installation. Due to docker limitation, the dockerized agent will only be available on Linux platforms (not Macos) so I guess the differents agent install methods will live together for a long time.
If you have time, give it a try (from a scratch install)

**Comment by chrisbehectik** [comment]
I couldn't get the agent working with the .env file, kept saying URL_MASTER was missing so I passed them directly in the compose file. Also, it seems that the variable is API_URL_MASTER. Example below for anyone else with the same issue:
```
  agent-ssm:
    container_name: agent-ssm
    image: ghcr.io/squirrelcorporation/squirrelserversmanager-agent:docker
    network_mode: host
    privileged: true
    pid: host
    environment:
      API_URL_MASTER: "https://ssm.domain.com"
      OVERRIDE_IP_DETECTION: "TAILSCALE-IP"
    restart: unless-stopped
    volumes:
      - /proc:/proc
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent-ssm/data:/data/
```
