### ISSUE TITLE
[BUG] Cannot reboot

### ISSUE THREAD

**Issue by windware-ono** [SquirrelCorporation/SquirrelServersManager#459]
**Describe the bug**
Reboot procedure fails. 

**To Reproduce**
1. Go to `Inventory`.
2. Hover above down arrow next to `Configuration`.
3. Click on `Reboot`.

**Expected behavior**
The target machine reboots.

**Screenshots**
<img width="982" alt="Screenshot 2024-11-12 at 8 08 43" src="https://github.com/user-attachments/assets/fd3d78af-8f9a-4866-9733-ce3fcfbf4dfe">

**(please complete the following information):**
 - OS: Ubuntu 24.04
 - Agent : NodeJS (Not enhanced one)

**Additional context**
I've commented out `Include` line within the container `squirrelserversmanager-server-1`'s `/etc/ssh/ssh_config` and part of that error disappears, but it still fails with the other error.

**Comment by SquirrelDeveloper** [comment]
Hi!
Could you try to edit the playbook _reboot in the Playbooks panel --> ssm-core / device / -reboot and add: 
- `become: true`

```yaml
---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Reboot
# Description: This playbook reboots unconditionally a machine
# Module: SSM-CORE
# Tags: reboot, restart, host

- hosts: all
  become: true
  tasks:
  - name: Unconditionally reboot the machine
    ansible.builtin.reboot:

```
