### ISSUE TITLE
[CHORE] Add elevation privilege test in check connection playbook

### ISSUE THREAD

**Issue by SquirrelDeveloper** [SquirrelCorporation/SquirrelServersManager#605]
Thanks, I'll look into if I can add the user securely to the Docker group but have avoided that so far.

For the Ansible become testing, the advanced diagnostics button tests SSH creds with the SSH login, SSH docker connect, ... testing the credentials and settings. What it does not test is the settings in the **Super User** agent config section which is used by Ansible become elevation.

As the installer for the agent requires elevation to be working, this test should actually be done in the connection test section to ensure the correct credentials are supplied.

I normally use the following to do the testing manually:
```yaml
---
- name: Test Sudo Working
  hosts: all
  tasks:
    - become: true
      command: id -u
      register: id_output

    - assert:
        that: id_output.stdout == '0'
```

_Originally posted by @ShaBangBinBash in https://github.com/SquirrelCorporation/SquirrelServersManager/issues/594#issuecomment-2560372079_
