### ISSUE TITLE
[BUG] prometheus seems to have no permissions on mount

### ISSUE THREAD

**Issue by mat-ti** [SquirrelCorporation/SquirrelServersManager#747]
**Describe the bug**
Promotheus Container restarts, when using your docker script (https://squirrelserversmanager.io/docs/quickstart)

**Logs**

```
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x3eae962, 0x5}, 0x14, 0xc0005d4fb0)
	/app/promql/query_logger.go:145 +0x345
main.main()
	/app/cmd/prometheus/main.go:791 +0x822c
time=2025-02-16T13:48:50.132Z level=INFO source=main.go:636 msg="No time or size retention was set so using the default time retention" duration=15d
time=2025-02-16T13:48:50.132Z level=INFO source=main.go:683 msg="Starting Prometheus Server" mode=server version="(version=3.1.0, branch=HEAD, revision=7086161a93b262aa0949dbf2aba15a5a7b13e0a3)"
time=2025-02-16T13:48:50.132Z level=INFO source=main.go:688 msg="operational information" build_context="(go=go1.23.4, platform=linux/amd64, user=root@74c225e2044f, date=20250102-13:52:43, tags=netgo,builtinassets,stringlabels)" host_details="(Linux 6.8.12-4-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-4 (2024-11-06T15:04Z) x86_64 a5ec0ffff8e6 (none))" fd_limits="(soft=524288, hard=524288)" vm_limits="(soft=unlimited, hard=unlimited)"
time=2025-02-16T13:48:50.134Z level=INFO source=main.go:764 msg="Leaving GOMAXPROCS=2: CPU quota undefined" component=automaxprocs
time=2025-02-16T13:48:50.135Z level=ERROR source=query_logger.go:137 msg="Failed to create directory for logging active queries" component=activeQueryTracker
time=2025-02-16T13:48:50.135Z level=ERROR source=query_logger.go:113 msg="Error opening query log file" component=activeQueryTracker file=/prometheus/data/queries.active err="open data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log
```

**To Reproduce**
1. by running  this command `curl -sL https://getssm.io | bash`

```
root@ssm:/opt/ssm# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Additional context**
No matter what os I'm using, tried alpine Linux and debian 12, the bug is raising everytime.

I can fix the issue by using a volume:
```
volumes:
  prometheus:

services:
 [...]
  prometheus:
    image: "ghcr.io/squirrelcorporation/squirrelserversmanager-prometheus:latest"
    container_name: prometheus-ssm
    restart: unless-stopped
    env_file: .env
    volumes:
      - prometheus:/prometheus
 [...]
```
