### ISSUE TITLE
[BUG] Cannot create a playbook on a local repository

### ISSUE THREAD

**Issue by Buco7854** [SquirrelCorporation/SquirrelServersManager#82]
**Describe the bug**
After creating a local repository it is not possible to add a file to it, it result in an error.
**Logs**
```
ERROR (1): [ERROR] 500 - E11000 duplicate key error collection: ssm.playbooks index: uniqueQuickRef_1 dup key: { uniqueQuickRef: null } - /playbooks-repository/d959dd36-2bc5-42dc-b390-85cf9b40db2e/playbook/test/ - PUT - 192.168.1.151
```

**To Reproduce**

1. Create a new local repository
2. Add a new file to it via the UI in the playbooks section.

**Expected behavior**
Should create the new playbook.

**Screenshots**
![image](https://github.com/SquirrelCorporation/SquirrelServersManager/assets/80671351/4b89e4bb-aae9-4457-a7ef-498927f0e3f9)

**Aditional Context**

I deleted the data dir for a new fresh install, still the same error.

My docker compose file : 

```yaml
version: "3.8"
services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
    ports:
      - 9050:8000
    depends_on:
      - client
      - mongo
      - server
      - redis
  mongo:
    container_name: mongo-ssm
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data.prod/db:/data/db
    command: --quiet
  redis:
    container_name: cache-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data.prod/cache:/data
    command: --save 60 1
  server:
    image: ghcr.io/squirrelcorporation/squirrelserversmanager-server:latest
    restart: unless-stopped
    external_links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - ./.data.prod/playbooks:/playbooks
  client:
    image: ghcr.io/squirrelcorporation/squirrelserversmanager-client:latest
    restart: unless-stopped
    depends_on:
      - server
```

 - Host OS: Debian 12 (bookworm)
 - Browser: Chrome
 - Browser Version: 126.0.6478.127
 - SSM Version: latest
